#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=98
STOP=10
USE_PROCD=1

service_triggers() {
    procd_add_reload_trigger network
}

start_service()
{
	procd_open_instance
	procd_set_param command /usr/sbin/mdns-repeater -f
	procd_set_param respawn
	procd_close_instance
}
